run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 50
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - google.golang.org/grpc
          - gopkg.in/yaml.v3
          - pulsecat/internal/app
          - pulsecat/internal/builder
          - pulsecat/internal/collector
          - pulsecat/internal/collector/average
          - pulsecat/internal/collector/builder
          - pulsecat/internal/config
          - pulsecat/internal/metrics
          - pulsecat/internal/runner
          - pulsecat/internal/server
          - pulsecat/internal/storage
          - pulsecat/internal/version
          - pulsecat/pkg/api/v1
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - pulsecat/internal/app
          - pulsecat/internal/builder
          - pulsecat/internal/collector
          - pulsecat/internal/collector/average
          - pulsecat/internal/collector/builder
          - pulsecat/internal/config
          - pulsecat/internal/metrics
          - pulsecat/internal/runner
          - pulsecat/internal/server
          - pulsecat/internal/storage
          - pulsecat/internal/version
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # - deadcode # deprecated - gave warning
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    # - exportloopref # deprecated - gave warning
    - funlen
    # - gci # demands different formatting than gci and always fails, cannot satisfy both
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt 
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - ifshort # deprecated - gave warning
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - structcheck # deprecated - gave warning
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck # deprecated - gave warning
    - wastedassign
    - whitespace
