// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/pulsecat.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricType enum for requested metric type
type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED           MetricType = 0
	MetricType_METRIC_TYPE_MEOW                  MetricType = 1
	MetricType_METRIC_TYPE_LOAD_AVERAGE          MetricType = 2
	MetricType_METRIC_TYPE_CPU_USAGE             MetricType = 3
	MetricType_METRIC_TYPE_DISK_USAGE            MetricType = 4
	MetricType_METRIC_TYPE_NETWORK_STATS         MetricType = 5
	MetricType_METRIC_TYPE_TOP_TALKERS           MetricType = 6
	MetricType_METRIC_TYPE_LISTENING_SOCKETS     MetricType = 7
	MetricType_METRIC_TYPE_TCP_CONNECTION_STATES MetricType = 8
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_MEOW",
		2: "METRIC_TYPE_LOAD_AVERAGE",
		3: "METRIC_TYPE_CPU_USAGE",
		4: "METRIC_TYPE_DISK_USAGE",
		5: "METRIC_TYPE_NETWORK_STATS",
		6: "METRIC_TYPE_TOP_TALKERS",
		7: "METRIC_TYPE_LISTENING_SOCKETS",
		8: "METRIC_TYPE_TCP_CONNECTION_STATES",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED":           0,
		"METRIC_TYPE_MEOW":                  1,
		"METRIC_TYPE_LOAD_AVERAGE":          2,
		"METRIC_TYPE_CPU_USAGE":             3,
		"METRIC_TYPE_DISK_USAGE":            4,
		"METRIC_TYPE_NETWORK_STATS":         5,
		"METRIC_TYPE_TOP_TALKERS":           6,
		"METRIC_TYPE_LISTENING_SOCKETS":     7,
		"METRIC_TYPE_TCP_CONNECTION_STATES": 8,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_pulsecat_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_v1_pulsecat_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{0}
}

// SubscribeRequest contains subscription parameters
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initial delay in seconds before first snapshot
	StartDelay uint32 `protobuf:"varint,1,opt,name=start_delay,json=startDelay,proto3" json:"start_delay,omitempty"`
	// Frequency in seconds between snapshots (0 = single snapshot)
	Frequency uint32 `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Requested metric type (only one metric per subscription)
	MetricType    MetricType `protobuf:"varint,3,opt,name=metric_type,json=metricType,proto3,enum=pulsecat.v1.MetricType" json:"metric_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetStartDelay() uint32 {
	if x != nil {
		return x.StartDelay
	}
	return 0
}

func (x *SubscribeRequest) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *SubscribeRequest) GetMetricType() MetricType {
	if x != nil {
		return x.MetricType
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

// MetricPulse contains a single metric snapshot
type MetricPulse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the snapshot (Unix epoch in seconds)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Metric:
	//
	//	*MetricPulse_Meow
	//	*MetricPulse_LoadAverage
	//	*MetricPulse_CpuUsage
	//	*MetricPulse_DiskUsage
	//	*MetricPulse_NetworkStats
	//	*MetricPulse_TopTalkers
	//	*MetricPulse_ListeningSockets
	//	*MetricPulse_TcpConnectionStates
	Metric        isMetricPulse_Metric `protobuf_oneof:"metric"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPulse) Reset() {
	*x = MetricPulse{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPulse) ProtoMessage() {}

func (x *MetricPulse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPulse.ProtoReflect.Descriptor instead.
func (*MetricPulse) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{1}
}

func (x *MetricPulse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricPulse) GetMetric() isMetricPulse_Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *MetricPulse) GetMeow() *Meow {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_Meow); ok {
			return x.Meow
		}
	}
	return nil
}

func (x *MetricPulse) GetLoadAverage() *LoadAverage {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_LoadAverage); ok {
			return x.LoadAverage
		}
	}
	return nil
}

func (x *MetricPulse) GetCpuUsage() *CPUUsage {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_CpuUsage); ok {
			return x.CpuUsage
		}
	}
	return nil
}

func (x *MetricPulse) GetDiskUsage() *DiskUsages {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_DiskUsage); ok {
			return x.DiskUsage
		}
	}
	return nil
}

func (x *MetricPulse) GetNetworkStats() *NetworkStats {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_NetworkStats); ok {
			return x.NetworkStats
		}
	}
	return nil
}

func (x *MetricPulse) GetTopTalkers() *NetworkTalkers {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_TopTalkers); ok {
			return x.TopTalkers
		}
	}
	return nil
}

func (x *MetricPulse) GetListeningSockets() *ListeningSockets {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_ListeningSockets); ok {
			return x.ListeningSockets
		}
	}
	return nil
}

func (x *MetricPulse) GetTcpConnectionStates() *TCPConnectionStates {
	if x != nil {
		if x, ok := x.Metric.(*MetricPulse_TcpConnectionStates); ok {
			return x.TcpConnectionStates
		}
	}
	return nil
}

type isMetricPulse_Metric interface {
	isMetricPulse_Metric()
}

type MetricPulse_Meow struct {
	Meow *Meow `protobuf:"bytes,2,opt,name=meow,proto3,oneof"`
}

type MetricPulse_LoadAverage struct {
	LoadAverage *LoadAverage `protobuf:"bytes,3,opt,name=load_average,json=loadAverage,proto3,oneof"`
}

type MetricPulse_CpuUsage struct {
	CpuUsage *CPUUsage `protobuf:"bytes,4,opt,name=cpu_usage,json=cpuUsage,proto3,oneof"`
}

type MetricPulse_DiskUsage struct {
	DiskUsage *DiskUsages `protobuf:"bytes,5,opt,name=disk_usage,json=diskUsage,proto3,oneof"`
}

type MetricPulse_NetworkStats struct {
	NetworkStats *NetworkStats `protobuf:"bytes,6,opt,name=network_stats,json=networkStats,proto3,oneof"`
}

type MetricPulse_TopTalkers struct {
	TopTalkers *NetworkTalkers `protobuf:"bytes,7,opt,name=top_talkers,json=topTalkers,proto3,oneof"`
}

type MetricPulse_ListeningSockets struct {
	ListeningSockets *ListeningSockets `protobuf:"bytes,8,opt,name=listening_sockets,json=listeningSockets,proto3,oneof"`
}

type MetricPulse_TcpConnectionStates struct {
	TcpConnectionStates *TCPConnectionStates `protobuf:"bytes,9,opt,name=tcp_connection_states,json=tcpConnectionStates,proto3,oneof"`
}

func (*MetricPulse_Meow) isMetricPulse_Metric() {}

func (*MetricPulse_LoadAverage) isMetricPulse_Metric() {}

func (*MetricPulse_CpuUsage) isMetricPulse_Metric() {}

func (*MetricPulse_DiskUsage) isMetricPulse_Metric() {}

func (*MetricPulse_NetworkStats) isMetricPulse_Metric() {}

func (*MetricPulse_TopTalkers) isMetricPulse_Metric() {}

func (*MetricPulse_ListeningSockets) isMetricPulse_Metric() {}

func (*MetricPulse_TcpConnectionStates) isMetricPulse_Metric() {}

// Meow contains the meow message (no timestamp, as it's included in MetricPulse)
type Meow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meow) Reset() {
	*x = Meow{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meow) ProtoMessage() {}

func (x *Meow) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meow.ProtoReflect.Descriptor instead.
func (*Meow) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{2}
}

func (x *Meow) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Wrapper messages for repeated fields (required for oneof)
type DiskUsages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*DiskUsage           `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsages) Reset() {
	*x = DiskUsages{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsages) ProtoMessage() {}

func (x *DiskUsages) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsages.ProtoReflect.Descriptor instead.
func (*DiskUsages) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{3}
}

func (x *DiskUsages) GetDisks() []*DiskUsage {
	if x != nil {
		return x.Disks
	}
	return nil
}

type NetworkTalkers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talkers       []*NetworkTalker       `protobuf:"bytes,1,rep,name=talkers,proto3" json:"talkers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkTalkers) Reset() {
	*x = NetworkTalkers{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTalkers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTalkers) ProtoMessage() {}

func (x *NetworkTalkers) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTalkers.ProtoReflect.Descriptor instead.
func (*NetworkTalkers) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkTalkers) GetTalkers() []*NetworkTalker {
	if x != nil {
		return x.Talkers
	}
	return nil
}

type ListeningSockets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sockets       []*ListeningSocket     `protobuf:"bytes,1,rep,name=sockets,proto3" json:"sockets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningSockets) Reset() {
	*x = ListeningSockets{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningSockets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningSockets) ProtoMessage() {}

func (x *ListeningSockets) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningSockets.ProtoReflect.Descriptor instead.
func (*ListeningSockets) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{5}
}

func (x *ListeningSockets) GetSockets() []*ListeningSocket {
	if x != nil {
		return x.Sockets
	}
	return nil
}

// LoadAverage represents system load averages
type LoadAverage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OneMin        float64                `protobuf:"fixed64,1,opt,name=one_min,json=oneMin,proto3" json:"one_min,omitempty"`
	FiveMin       float64                `protobuf:"fixed64,2,opt,name=five_min,json=fiveMin,proto3" json:"five_min,omitempty"`
	FifteenMin    float64                `protobuf:"fixed64,3,opt,name=fifteen_min,json=fifteenMin,proto3" json:"fifteen_min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{6}
}

func (x *LoadAverage) GetOneMin() float64 {
	if x != nil {
		return x.OneMin
	}
	return 0
}

func (x *LoadAverage) GetFiveMin() float64 {
	if x != nil {
		return x.FiveMin
	}
	return 0
}

func (x *LoadAverage) GetFifteenMin() float64 {
	if x != nil {
		return x.FifteenMin
	}
	return 0
}

// CPUUsage represents CPU usage percentages
type CPUUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          float64                `protobuf:"fixed64,1,opt,name=user,proto3" json:"user,omitempty"`
	System        float64                `protobuf:"fixed64,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle          float64                `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
	Nice          float64                `protobuf:"fixed64,4,opt,name=nice,proto3" json:"nice,omitempty"`
	Iowait        float64                `protobuf:"fixed64,5,opt,name=iowait,proto3" json:"iowait,omitempty"`
	Irq           float64                `protobuf:"fixed64,6,opt,name=irq,proto3" json:"irq,omitempty"`
	SoftIrq       float64                `protobuf:"fixed64,7,opt,name=soft_irq,json=softIrq,proto3" json:"soft_irq,omitempty"`
	Steal         float64                `protobuf:"fixed64,8,opt,name=steal,proto3" json:"steal,omitempty"`
	Guest         float64                `protobuf:"fixed64,9,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUUsage) Reset() {
	*x = CPUUsage{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUUsage) ProtoMessage() {}

func (x *CPUUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUUsage.ProtoReflect.Descriptor instead.
func (*CPUUsage) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{7}
}

func (x *CPUUsage) GetUser() float64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CPUUsage) GetSystem() float64 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CPUUsage) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *CPUUsage) GetNice() float64 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *CPUUsage) GetIowait() float64 {
	if x != nil {
		return x.Iowait
	}
	return 0
}

func (x *CPUUsage) GetIrq() float64 {
	if x != nil {
		return x.Irq
	}
	return 0
}

func (x *CPUUsage) GetSoftIrq() float64 {
	if x != nil {
		return x.SoftIrq
	}
	return 0
}

func (x *CPUUsage) GetSteal() float64 {
	if x != nil {
		return x.Steal
	}
	return 0
}

func (x *CPUUsage) GetGuest() float64 {
	if x != nil {
		return x.Guest
	}
	return 0
}

// DiskUsage represents disk usage for a filesystem
type DiskUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filesystem        string                 `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	TotalMb           uint64                 `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb            uint64                 `protobuf:"varint,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	AvailableMb       uint64                 `protobuf:"varint,4,opt,name=available_mb,json=availableMb,proto3" json:"available_mb,omitempty"`
	UsedPercent       float64                `protobuf:"fixed64,5,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	TotalInodes       uint64                 `protobuf:"varint,6,opt,name=total_inodes,json=totalInodes,proto3" json:"total_inodes,omitempty"`
	UsedInodes        uint64                 `protobuf:"varint,7,opt,name=used_inodes,json=usedInodes,proto3" json:"used_inodes,omitempty"`
	UsedInodesPercent float64                `protobuf:"fixed64,8,opt,name=used_inodes_percent,json=usedInodesPercent,proto3" json:"used_inodes_percent,omitempty"`
	MountPoint        string                 `protobuf:"bytes,9,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{8}
}

func (x *DiskUsage) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DiskUsage) GetTotalMb() uint64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *DiskUsage) GetUsedMb() uint64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *DiskUsage) GetAvailableMb() uint64 {
	if x != nil {
		return x.AvailableMb
	}
	return 0
}

func (x *DiskUsage) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *DiskUsage) GetTotalInodes() uint64 {
	if x != nil {
		return x.TotalInodes
	}
	return 0
}

func (x *DiskUsage) GetUsedInodes() uint64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

func (x *DiskUsage) GetUsedInodesPercent() float64 {
	if x != nil {
		return x.UsedInodesPercent
	}
	return 0
}

func (x *DiskUsage) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

// NetworkStats contains overall network statistics
type NetworkStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalBytesReceived uint64                 `protobuf:"varint,1,opt,name=total_bytes_received,json=totalBytesReceived,proto3" json:"total_bytes_received,omitempty"`
	TotalBytesSent     uint64                 `protobuf:"varint,2,opt,name=total_bytes_sent,json=totalBytesSent,proto3" json:"total_bytes_sent,omitempty"`
	PacketsReceived    uint64                 `protobuf:"varint,3,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsSent        uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	ErrorsReceived     uint64                 `protobuf:"varint,5,opt,name=errors_received,json=errorsReceived,proto3" json:"errors_received,omitempty"`
	ErrorsSent         uint64                 `protobuf:"varint,6,opt,name=errors_sent,json=errorsSent,proto3" json:"errors_sent,omitempty"`
	DropsReceived      uint64                 `protobuf:"varint,7,opt,name=drops_received,json=dropsReceived,proto3" json:"drops_received,omitempty"`
	DropsSent          uint64                 `protobuf:"varint,8,opt,name=drops_sent,json=dropsSent,proto3" json:"drops_sent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkStats) GetTotalBytesReceived() uint64 {
	if x != nil {
		return x.TotalBytesReceived
	}
	return 0
}

func (x *NetworkStats) GetTotalBytesSent() uint64 {
	if x != nil {
		return x.TotalBytesSent
	}
	return 0
}

func (x *NetworkStats) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *NetworkStats) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetworkStats) GetErrorsReceived() uint64 {
	if x != nil {
		return x.ErrorsReceived
	}
	return 0
}

func (x *NetworkStats) GetErrorsSent() uint64 {
	if x != nil {
		return x.ErrorsSent
	}
	return 0
}

func (x *NetworkStats) GetDropsReceived() uint64 {
	if x != nil {
		return x.DropsReceived
	}
	return 0
}

func (x *NetworkStats) GetDropsSent() uint64 {
	if x != nil {
		return x.DropsSent
	}
	return 0
}

// NetworkTalker represents a top network talker
type NetworkTalker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*NetworkTalker_Protocol
	//	*NetworkTalker_Connection
	Identifier     isNetworkTalker_Identifier `protobuf_oneof:"identifier"`
	BytesPerSecond uint64                     `protobuf:"varint,3,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	Percentage     float64                    `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkTalker) Reset() {
	*x = NetworkTalker{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTalker) ProtoMessage() {}

func (x *NetworkTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTalker.ProtoReflect.Descriptor instead.
func (*NetworkTalker) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkTalker) GetIdentifier() isNetworkTalker_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *NetworkTalker) GetProtocol() *ProtocolTalker {
	if x != nil {
		if x, ok := x.Identifier.(*NetworkTalker_Protocol); ok {
			return x.Protocol
		}
	}
	return nil
}

func (x *NetworkTalker) GetConnection() *ConnectionTalker {
	if x != nil {
		if x, ok := x.Identifier.(*NetworkTalker_Connection); ok {
			return x.Connection
		}
	}
	return nil
}

func (x *NetworkTalker) GetBytesPerSecond() uint64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *NetworkTalker) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type isNetworkTalker_Identifier interface {
	isNetworkTalker_Identifier()
}

type NetworkTalker_Protocol struct {
	Protocol *ProtocolTalker `protobuf:"bytes,1,opt,name=protocol,proto3,oneof"`
}

type NetworkTalker_Connection struct {
	Connection *ConnectionTalker `protobuf:"bytes,2,opt,name=connection,proto3,oneof"`
}

func (*NetworkTalker_Protocol) isNetworkTalker_Identifier() {}

func (*NetworkTalker_Connection) isNetworkTalker_Identifier() {}

// ProtocolTalker identifies traffic by protocol
type ProtocolTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP, ICMP, etc.
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`        // Optional port for protocol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolTalker) Reset() {
	*x = ProtocolTalker{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolTalker) ProtoMessage() {}

func (x *ProtocolTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolTalker.ProtoReflect.Descriptor instead.
func (*ProtocolTalker) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{11}
}

func (x *ProtocolTalker) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolTalker) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// ConnectionTalker identifies traffic by connection
type ConnectionTalker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceIp        string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort      uint32                 `protobuf:"varint,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp   string                 `protobuf:"bytes,3,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort uint32                 `protobuf:"varint,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectionTalker) Reset() {
	*x = ConnectionTalker{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTalker) ProtoMessage() {}

func (x *ConnectionTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTalker.ProtoReflect.Descriptor instead.
func (*ConnectionTalker) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectionTalker) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ConnectionTalker) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *ConnectionTalker) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *ConnectionTalker) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *ConnectionTalker) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// ListeningSocket represents a listening network socket
type ListeningSocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningSocket) Reset() {
	*x = ListeningSocket{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningSocket) ProtoMessage() {}

func (x *ListeningSocket) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningSocket.ProtoReflect.Descriptor instead.
func (*ListeningSocket) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{13}
}

func (x *ListeningSocket) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ListeningSocket) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListeningSocket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListeningSocket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListeningSocket) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListeningSocket) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// TCPConnectionStates contains counts of TCP connections in various states
type TCPConnectionStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Established   uint32                 `protobuf:"varint,1,opt,name=established,proto3" json:"established,omitempty"`
	SynSent       uint32                 `protobuf:"varint,2,opt,name=syn_sent,json=synSent,proto3" json:"syn_sent,omitempty"`
	SynRecv       uint32                 `protobuf:"varint,3,opt,name=syn_recv,json=synRecv,proto3" json:"syn_recv,omitempty"`
	FinWait1      uint32                 `protobuf:"varint,4,opt,name=fin_wait1,json=finWait1,proto3" json:"fin_wait1,omitempty"`
	FinWait2      uint32                 `protobuf:"varint,5,opt,name=fin_wait2,json=finWait2,proto3" json:"fin_wait2,omitempty"`
	TimeWait      uint32                 `protobuf:"varint,6,opt,name=time_wait,json=timeWait,proto3" json:"time_wait,omitempty"`
	Close         uint32                 `protobuf:"varint,7,opt,name=close,proto3" json:"close,omitempty"`
	CloseWait     uint32                 `protobuf:"varint,8,opt,name=close_wait,json=closeWait,proto3" json:"close_wait,omitempty"`
	LastAck       uint32                 `protobuf:"varint,9,opt,name=last_ack,json=lastAck,proto3" json:"last_ack,omitempty"`
	Listen        uint32                 `protobuf:"varint,10,opt,name=listen,proto3" json:"listen,omitempty"`
	Closing       uint32                 `protobuf:"varint,11,opt,name=closing,proto3" json:"closing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPConnectionStates) Reset() {
	*x = TCPConnectionStates{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPConnectionStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPConnectionStates) ProtoMessage() {}

func (x *TCPConnectionStates) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPConnectionStates.ProtoReflect.Descriptor instead.
func (*TCPConnectionStates) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{14}
}

func (x *TCPConnectionStates) GetEstablished() uint32 {
	if x != nil {
		return x.Established
	}
	return 0
}

func (x *TCPConnectionStates) GetSynSent() uint32 {
	if x != nil {
		return x.SynSent
	}
	return 0
}

func (x *TCPConnectionStates) GetSynRecv() uint32 {
	if x != nil {
		return x.SynRecv
	}
	return 0
}

func (x *TCPConnectionStates) GetFinWait1() uint32 {
	if x != nil {
		return x.FinWait1
	}
	return 0
}

func (x *TCPConnectionStates) GetFinWait2() uint32 {
	if x != nil {
		return x.FinWait2
	}
	return 0
}

func (x *TCPConnectionStates) GetTimeWait() uint32 {
	if x != nil {
		return x.TimeWait
	}
	return 0
}

func (x *TCPConnectionStates) GetClose() uint32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *TCPConnectionStates) GetCloseWait() uint32 {
	if x != nil {
		return x.CloseWait
	}
	return 0
}

func (x *TCPConnectionStates) GetLastAck() uint32 {
	if x != nil {
		return x.LastAck
	}
	return 0
}

func (x *TCPConnectionStates) GetListen() uint32 {
	if x != nil {
		return x.Listen
	}
	return 0
}

func (x *TCPConnectionStates) GetClosing() uint32 {
	if x != nil {
		return x.Closing
	}
	return 0
}

var File_api_v1_pulsecat_proto protoreflect.FileDescriptor

const file_api_v1_pulsecat_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/pulsecat.proto\x12\vpulsecat.v1\"\x8b\x01\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vstart_delay\x18\x01 \x01(\rR\n" +
	"startDelay\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\rR\tfrequency\x128\n" +
	"\vmetric_type\x18\x03 \x01(\x0e2\x17.pulsecat.v1.MetricTypeR\n" +
	"metricType\"\xb5\x04\n" +
	"\vMetricPulse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12'\n" +
	"\x04meow\x18\x02 \x01(\v2\x11.pulsecat.v1.MeowH\x00R\x04meow\x12=\n" +
	"\fload_average\x18\x03 \x01(\v2\x18.pulsecat.v1.LoadAverageH\x00R\vloadAverage\x124\n" +
	"\tcpu_usage\x18\x04 \x01(\v2\x15.pulsecat.v1.CPUUsageH\x00R\bcpuUsage\x128\n" +
	"\n" +
	"disk_usage\x18\x05 \x01(\v2\x17.pulsecat.v1.DiskUsagesH\x00R\tdiskUsage\x12@\n" +
	"\rnetwork_stats\x18\x06 \x01(\v2\x19.pulsecat.v1.NetworkStatsH\x00R\fnetworkStats\x12>\n" +
	"\vtop_talkers\x18\a \x01(\v2\x1b.pulsecat.v1.NetworkTalkersH\x00R\n" +
	"topTalkers\x12L\n" +
	"\x11listening_sockets\x18\b \x01(\v2\x1d.pulsecat.v1.ListeningSocketsH\x00R\x10listeningSockets\x12V\n" +
	"\x15tcp_connection_states\x18\t \x01(\v2 .pulsecat.v1.TCPConnectionStatesH\x00R\x13tcpConnectionStatesB\b\n" +
	"\x06metric\" \n" +
	"\x04Meow\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\n" +
	"DiskUsages\x12,\n" +
	"\x05disks\x18\x01 \x03(\v2\x16.pulsecat.v1.DiskUsageR\x05disks\"F\n" +
	"\x0eNetworkTalkers\x124\n" +
	"\atalkers\x18\x01 \x03(\v2\x1a.pulsecat.v1.NetworkTalkerR\atalkers\"J\n" +
	"\x10ListeningSockets\x126\n" +
	"\asockets\x18\x01 \x03(\v2\x1c.pulsecat.v1.ListeningSocketR\asockets\"b\n" +
	"\vLoadAverage\x12\x17\n" +
	"\aone_min\x18\x01 \x01(\x01R\x06oneMin\x12\x19\n" +
	"\bfive_min\x18\x02 \x01(\x01R\afiveMin\x12\x1f\n" +
	"\vfifteen_min\x18\x03 \x01(\x01R\n" +
	"fifteenMin\"\xcf\x01\n" +
	"\bCPUUsage\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x01R\x04user\x12\x16\n" +
	"\x06system\x18\x02 \x01(\x01R\x06system\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x01R\x04idle\x12\x12\n" +
	"\x04nice\x18\x04 \x01(\x01R\x04nice\x12\x16\n" +
	"\x06iowait\x18\x05 \x01(\x01R\x06iowait\x12\x10\n" +
	"\x03irq\x18\x06 \x01(\x01R\x03irq\x12\x19\n" +
	"\bsoft_irq\x18\a \x01(\x01R\asoftIrq\x12\x14\n" +
	"\x05steal\x18\b \x01(\x01R\x05steal\x12\x14\n" +
	"\x05guest\x18\t \x01(\x01R\x05guest\"\xba\x02\n" +
	"\tDiskUsage\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\tR\n" +
	"filesystem\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x04R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x04R\x06usedMb\x12!\n" +
	"\favailable_mb\x18\x04 \x01(\x04R\vavailableMb\x12!\n" +
	"\fused_percent\x18\x05 \x01(\x01R\vusedPercent\x12!\n" +
	"\ftotal_inodes\x18\x06 \x01(\x04R\vtotalInodes\x12\x1f\n" +
	"\vused_inodes\x18\a \x01(\x04R\n" +
	"usedInodes\x12.\n" +
	"\x13used_inodes_percent\x18\b \x01(\x01R\x11usedInodesPercent\x12\x1f\n" +
	"\vmount_point\x18\t \x01(\tR\n" +
	"mountPoint\"\xc8\x02\n" +
	"\fNetworkStats\x120\n" +
	"\x14total_bytes_received\x18\x01 \x01(\x04R\x12totalBytesReceived\x12(\n" +
	"\x10total_bytes_sent\x18\x02 \x01(\x04R\x0etotalBytesSent\x12)\n" +
	"\x10packets_received\x18\x03 \x01(\x04R\x0fpacketsReceived\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12'\n" +
	"\x0ferrors_received\x18\x05 \x01(\x04R\x0eerrorsReceived\x12\x1f\n" +
	"\verrors_sent\x18\x06 \x01(\x04R\n" +
	"errorsSent\x12%\n" +
	"\x0edrops_received\x18\a \x01(\x04R\rdropsReceived\x12\x1d\n" +
	"\n" +
	"drops_sent\x18\b \x01(\x04R\tdropsSent\"\xe3\x01\n" +
	"\rNetworkTalker\x129\n" +
	"\bprotocol\x18\x01 \x01(\v2\x1b.pulsecat.v1.ProtocolTalkerH\x00R\bprotocol\x12?\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1d.pulsecat.v1.ConnectionTalkerH\x00R\n" +
	"connection\x12(\n" +
	"\x10bytes_per_second\x18\x03 \x01(\x04R\x0ebytesPerSecond\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentageB\f\n" +
	"\n" +
	"identifier\"@\n" +
	"\x0eProtocolTalker\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\xbe\x01\n" +
	"\x10ConnectionTalker\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x02 \x01(\rR\n" +
	"sourcePort\x12%\n" +
	"\x0edestination_ip\x18\x03 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x04 \x01(\rR\x0fdestinationPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"\x9b\x01\n" +
	"\x0fListeningSocket\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"\xc6\x02\n" +
	"\x13TCPConnectionStates\x12 \n" +
	"\vestablished\x18\x01 \x01(\rR\vestablished\x12\x19\n" +
	"\bsyn_sent\x18\x02 \x01(\rR\asynSent\x12\x19\n" +
	"\bsyn_recv\x18\x03 \x01(\rR\asynRecv\x12\x1b\n" +
	"\tfin_wait1\x18\x04 \x01(\rR\bfinWait1\x12\x1b\n" +
	"\tfin_wait2\x18\x05 \x01(\rR\bfinWait2\x12\x1b\n" +
	"\ttime_wait\x18\x06 \x01(\rR\btimeWait\x12\x14\n" +
	"\x05close\x18\a \x01(\rR\x05close\x12\x1d\n" +
	"\n" +
	"close_wait\x18\b \x01(\rR\tcloseWait\x12\x19\n" +
	"\blast_ack\x18\t \x01(\rR\alastAck\x12\x16\n" +
	"\x06listen\x18\n" +
	" \x01(\rR\x06listen\x12\x18\n" +
	"\aclosing\x18\v \x01(\rR\aclosing*\x9a\x02\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10METRIC_TYPE_MEOW\x10\x01\x12\x1c\n" +
	"\x18METRIC_TYPE_LOAD_AVERAGE\x10\x02\x12\x19\n" +
	"\x15METRIC_TYPE_CPU_USAGE\x10\x03\x12\x1a\n" +
	"\x16METRIC_TYPE_DISK_USAGE\x10\x04\x12\x1d\n" +
	"\x19METRIC_TYPE_NETWORK_STATS\x10\x05\x12\x1b\n" +
	"\x17METRIC_TYPE_TOP_TALKERS\x10\x06\x12!\n" +
	"\x1dMETRIC_TYPE_LISTENING_SOCKETS\x10\a\x12%\n" +
	"!METRIC_TYPE_TCP_CONNECTION_STATES\x10\b2T\n" +
	"\bPulseCat\x12H\n" +
	"\tSubscribe\x12\x1d.pulsecat.v1.SubscribeRequest\x1a\x18.pulsecat.v1.MetricPulse\"\x000\x01B\x11Z\x0fpulsecat/api/v1b\x06proto3"

var (
	file_api_v1_pulsecat_proto_rawDescOnce sync.Once
	file_api_v1_pulsecat_proto_rawDescData []byte
)

func file_api_v1_pulsecat_proto_rawDescGZIP() []byte {
	file_api_v1_pulsecat_proto_rawDescOnce.Do(func() {
		file_api_v1_pulsecat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_pulsecat_proto_rawDesc), len(file_api_v1_pulsecat_proto_rawDesc)))
	})
	return file_api_v1_pulsecat_proto_rawDescData
}

var (
	file_api_v1_pulsecat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_api_v1_pulsecat_proto_msgTypes  = make([]protoimpl.MessageInfo, 15)
	file_api_v1_pulsecat_proto_goTypes   = []any{
		(MetricType)(0),             // 0: pulsecat.v1.MetricType
		(*SubscribeRequest)(nil),    // 1: pulsecat.v1.SubscribeRequest
		(*MetricPulse)(nil),         // 2: pulsecat.v1.MetricPulse
		(*Meow)(nil),                // 3: pulsecat.v1.Meow
		(*DiskUsages)(nil),          // 4: pulsecat.v1.DiskUsages
		(*NetworkTalkers)(nil),      // 5: pulsecat.v1.NetworkTalkers
		(*ListeningSockets)(nil),    // 6: pulsecat.v1.ListeningSockets
		(*LoadAverage)(nil),         // 7: pulsecat.v1.LoadAverage
		(*CPUUsage)(nil),            // 8: pulsecat.v1.CPUUsage
		(*DiskUsage)(nil),           // 9: pulsecat.v1.DiskUsage
		(*NetworkStats)(nil),        // 10: pulsecat.v1.NetworkStats
		(*NetworkTalker)(nil),       // 11: pulsecat.v1.NetworkTalker
		(*ProtocolTalker)(nil),      // 12: pulsecat.v1.ProtocolTalker
		(*ConnectionTalker)(nil),    // 13: pulsecat.v1.ConnectionTalker
		(*ListeningSocket)(nil),     // 14: pulsecat.v1.ListeningSocket
		(*TCPConnectionStates)(nil), // 15: pulsecat.v1.TCPConnectionStates
	}
)

var file_api_v1_pulsecat_proto_depIdxs = []int32{
	0,  // 0: pulsecat.v1.SubscribeRequest.metric_type:type_name -> pulsecat.v1.MetricType
	3,  // 1: pulsecat.v1.MetricPulse.meow:type_name -> pulsecat.v1.Meow
	7,  // 2: pulsecat.v1.MetricPulse.load_average:type_name -> pulsecat.v1.LoadAverage
	8,  // 3: pulsecat.v1.MetricPulse.cpu_usage:type_name -> pulsecat.v1.CPUUsage
	4,  // 4: pulsecat.v1.MetricPulse.disk_usage:type_name -> pulsecat.v1.DiskUsages
	10, // 5: pulsecat.v1.MetricPulse.network_stats:type_name -> pulsecat.v1.NetworkStats
	5,  // 6: pulsecat.v1.MetricPulse.top_talkers:type_name -> pulsecat.v1.NetworkTalkers
	6,  // 7: pulsecat.v1.MetricPulse.listening_sockets:type_name -> pulsecat.v1.ListeningSockets
	15, // 8: pulsecat.v1.MetricPulse.tcp_connection_states:type_name -> pulsecat.v1.TCPConnectionStates
	9,  // 9: pulsecat.v1.DiskUsages.disks:type_name -> pulsecat.v1.DiskUsage
	11, // 10: pulsecat.v1.NetworkTalkers.talkers:type_name -> pulsecat.v1.NetworkTalker
	14, // 11: pulsecat.v1.ListeningSockets.sockets:type_name -> pulsecat.v1.ListeningSocket
	12, // 12: pulsecat.v1.NetworkTalker.protocol:type_name -> pulsecat.v1.ProtocolTalker
	13, // 13: pulsecat.v1.NetworkTalker.connection:type_name -> pulsecat.v1.ConnectionTalker
	1,  // 14: pulsecat.v1.PulseCat.Subscribe:input_type -> pulsecat.v1.SubscribeRequest
	2,  // 15: pulsecat.v1.PulseCat.Subscribe:output_type -> pulsecat.v1.MetricPulse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_v1_pulsecat_proto_init() }
func file_api_v1_pulsecat_proto_init() {
	if File_api_v1_pulsecat_proto != nil {
		return
	}
	file_api_v1_pulsecat_proto_msgTypes[1].OneofWrappers = []any{
		(*MetricPulse_Meow)(nil),
		(*MetricPulse_LoadAverage)(nil),
		(*MetricPulse_CpuUsage)(nil),
		(*MetricPulse_DiskUsage)(nil),
		(*MetricPulse_NetworkStats)(nil),
		(*MetricPulse_TopTalkers)(nil),
		(*MetricPulse_ListeningSockets)(nil),
		(*MetricPulse_TcpConnectionStates)(nil),
	}
	file_api_v1_pulsecat_proto_msgTypes[10].OneofWrappers = []any{
		(*NetworkTalker_Protocol)(nil),
		(*NetworkTalker_Connection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_pulsecat_proto_rawDesc), len(file_api_v1_pulsecat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_pulsecat_proto_goTypes,
		DependencyIndexes: file_api_v1_pulsecat_proto_depIdxs,
		EnumInfos:         file_api_v1_pulsecat_proto_enumTypes,
		MessageInfos:      file_api_v1_pulsecat_proto_msgTypes,
	}.Build()
	File_api_v1_pulsecat_proto = out.File
	file_api_v1_pulsecat_proto_goTypes = nil
	file_api_v1_pulsecat_proto_depIdxs = nil
}
