// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/pulsecat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatType enum for filtering requested statistics
type StatType int32

const (
	StatType_STAT_TYPE_UNSPECIFIED           StatType = 0
	StatType_STAT_TYPE_LOAD_AVERAGE          StatType = 1
	StatType_STAT_TYPE_CPU_USAGE             StatType = 2
	StatType_STAT_TYPE_DISK_USAGE            StatType = 3
	StatType_STAT_TYPE_NETWORK_STATS         StatType = 4
	StatType_STAT_TYPE_TOP_TALKERS           StatType = 5
	StatType_STAT_TYPE_LISTENING_SOCKETS     StatType = 6
	StatType_STAT_TYPE_TCP_CONNECTION_STATES StatType = 7
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "STAT_TYPE_UNSPECIFIED",
		1: "STAT_TYPE_LOAD_AVERAGE",
		2: "STAT_TYPE_CPU_USAGE",
		3: "STAT_TYPE_DISK_USAGE",
		4: "STAT_TYPE_NETWORK_STATS",
		5: "STAT_TYPE_TOP_TALKERS",
		6: "STAT_TYPE_LISTENING_SOCKETS",
		7: "STAT_TYPE_TCP_CONNECTION_STATES",
	}
	StatType_value = map[string]int32{
		"STAT_TYPE_UNSPECIFIED":           0,
		"STAT_TYPE_LOAD_AVERAGE":          1,
		"STAT_TYPE_CPU_USAGE":             2,
		"STAT_TYPE_DISK_USAGE":            3,
		"STAT_TYPE_NETWORK_STATS":         4,
		"STAT_TYPE_TOP_TALKERS":           5,
		"STAT_TYPE_LISTENING_SOCKETS":     6,
		"STAT_TYPE_TCP_CONNECTION_STATES": 7,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_pulsecat_proto_enumTypes[0].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_api_v1_pulsecat_proto_enumTypes[0]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{0}
}

// SubscribeRequest contains subscription parameters
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// M: Initial delay in seconds before first snapshot
	StartDelay uint32 `protobuf:"varint,1,opt,name=start_delay,json=startDelay,proto3" json:"start_delay,omitempty"`
	// N: Frequency in seconds between snapshots
	Frequency uint32 `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Optional: Filter for specific statistics
	StatTypes     []StatType `protobuf:"varint,3,rep,packed,name=stat_types,json=statTypes,proto3,enum=pulsecat.v1.StatType" json:"stat_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetStartDelay() uint32 {
	if x != nil {
		return x.StartDelay
	}
	return 0
}

func (x *SubscribeRequest) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *SubscribeRequest) GetStatTypes() []StatType {
	if x != nil {
		return x.StatTypes
	}
	return nil
}

// SystemStats contains comprehensive system statistics
type SystemStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the snapshot (Unix epoch in seconds)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// System load averages
	LoadAverage *LoadAverage `protobuf:"bytes,2,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	// CPU usage statistics
	CpuUsage *CpuUsage `protobuf:"bytes,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Disk usage information
	DiskUsage []*DiskUsage `protobuf:"bytes,4,rep,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	// Network statistics
	NetworkStats *NetworkStats `protobuf:"bytes,5,opt,name=network_stats,json=networkStats,proto3" json:"network_stats,omitempty"`
	// Top network talkers
	TopTalkers []*NetworkTalker `protobuf:"bytes,6,rep,name=top_talkers,json=topTalkers,proto3" json:"top_talkers,omitempty"`
	// Listening sockets
	ListeningSockets []*ListeningSocket `protobuf:"bytes,7,rep,name=listening_sockets,json=listeningSockets,proto3" json:"listening_sockets,omitempty"`
	// TCP connection states
	TcpConnectionStates *TcpConnectionStates `protobuf:"bytes,8,opt,name=tcp_connection_states,json=tcpConnectionStates,proto3" json:"tcp_connection_states,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{1}
}

func (x *SystemStats) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SystemStats) GetLoadAverage() *LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *SystemStats) GetCpuUsage() *CpuUsage {
	if x != nil {
		return x.CpuUsage
	}
	return nil
}

func (x *SystemStats) GetDiskUsage() []*DiskUsage {
	if x != nil {
		return x.DiskUsage
	}
	return nil
}

func (x *SystemStats) GetNetworkStats() *NetworkStats {
	if x != nil {
		return x.NetworkStats
	}
	return nil
}

func (x *SystemStats) GetTopTalkers() []*NetworkTalker {
	if x != nil {
		return x.TopTalkers
	}
	return nil
}

func (x *SystemStats) GetListeningSockets() []*ListeningSocket {
	if x != nil {
		return x.ListeningSockets
	}
	return nil
}

func (x *SystemStats) GetTcpConnectionStates() *TcpConnectionStates {
	if x != nil {
		return x.TcpConnectionStates
	}
	return nil
}

// LoadAverage represents system load averages
type LoadAverage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OneMin        float64                `protobuf:"fixed64,1,opt,name=one_min,json=oneMin,proto3" json:"one_min,omitempty"`
	FiveMin       float64                `protobuf:"fixed64,2,opt,name=five_min,json=fiveMin,proto3" json:"five_min,omitempty"`
	FifteenMin    float64                `protobuf:"fixed64,3,opt,name=fifteen_min,json=fifteenMin,proto3" json:"fifteen_min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAverage) GetOneMin() float64 {
	if x != nil {
		return x.OneMin
	}
	return 0
}

func (x *LoadAverage) GetFiveMin() float64 {
	if x != nil {
		return x.FiveMin
	}
	return 0
}

func (x *LoadAverage) GetFifteenMin() float64 {
	if x != nil {
		return x.FifteenMin
	}
	return 0
}

// CpuUsage represents CPU usage percentages
type CpuUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          float64                `protobuf:"fixed64,1,opt,name=user,proto3" json:"user,omitempty"`
	System        float64                `protobuf:"fixed64,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle          float64                `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
	Nice          float64                `protobuf:"fixed64,4,opt,name=nice,proto3" json:"nice,omitempty"`
	Iowait        float64                `protobuf:"fixed64,5,opt,name=iowait,proto3" json:"iowait,omitempty"`
	Irq           float64                `protobuf:"fixed64,6,opt,name=irq,proto3" json:"irq,omitempty"`
	SoftIrq       float64                `protobuf:"fixed64,7,opt,name=soft_irq,json=softIrq,proto3" json:"soft_irq,omitempty"`
	Steal         float64                `protobuf:"fixed64,8,opt,name=steal,proto3" json:"steal,omitempty"`
	Guest         float64                `protobuf:"fixed64,9,opt,name=guest,proto3" json:"guest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuUsage) Reset() {
	*x = CpuUsage{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuUsage) ProtoMessage() {}

func (x *CpuUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuUsage.ProtoReflect.Descriptor instead.
func (*CpuUsage) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{3}
}

func (x *CpuUsage) GetUser() float64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CpuUsage) GetSystem() float64 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CpuUsage) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *CpuUsage) GetNice() float64 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *CpuUsage) GetIowait() float64 {
	if x != nil {
		return x.Iowait
	}
	return 0
}

func (x *CpuUsage) GetIrq() float64 {
	if x != nil {
		return x.Irq
	}
	return 0
}

func (x *CpuUsage) GetSoftIrq() float64 {
	if x != nil {
		return x.SoftIrq
	}
	return 0
}

func (x *CpuUsage) GetSteal() float64 {
	if x != nil {
		return x.Steal
	}
	return 0
}

func (x *CpuUsage) GetGuest() float64 {
	if x != nil {
		return x.Guest
	}
	return 0
}

// DiskUsage represents disk usage for a filesystem
type DiskUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filesystem        string                 `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	TotalMb           uint64                 `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb            uint64                 `protobuf:"varint,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	AvailableMb       uint64                 `protobuf:"varint,4,opt,name=available_mb,json=availableMb,proto3" json:"available_mb,omitempty"`
	UsedPercent       float64                `protobuf:"fixed64,5,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	TotalInodes       uint64                 `protobuf:"varint,6,opt,name=total_inodes,json=totalInodes,proto3" json:"total_inodes,omitempty"`
	UsedInodes        uint64                 `protobuf:"varint,7,opt,name=used_inodes,json=usedInodes,proto3" json:"used_inodes,omitempty"`
	UsedInodesPercent float64                `protobuf:"fixed64,8,opt,name=used_inodes_percent,json=usedInodesPercent,proto3" json:"used_inodes_percent,omitempty"`
	MountPoint        string                 `protobuf:"bytes,9,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{4}
}

func (x *DiskUsage) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *DiskUsage) GetTotalMb() uint64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *DiskUsage) GetUsedMb() uint64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *DiskUsage) GetAvailableMb() uint64 {
	if x != nil {
		return x.AvailableMb
	}
	return 0
}

func (x *DiskUsage) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *DiskUsage) GetTotalInodes() uint64 {
	if x != nil {
		return x.TotalInodes
	}
	return 0
}

func (x *DiskUsage) GetUsedInodes() uint64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

func (x *DiskUsage) GetUsedInodesPercent() float64 {
	if x != nil {
		return x.UsedInodesPercent
	}
	return 0
}

func (x *DiskUsage) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

// NetworkStats contains overall network statistics
type NetworkStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalBytesReceived uint64                 `protobuf:"varint,1,opt,name=total_bytes_received,json=totalBytesReceived,proto3" json:"total_bytes_received,omitempty"`
	TotalBytesSent     uint64                 `protobuf:"varint,2,opt,name=total_bytes_sent,json=totalBytesSent,proto3" json:"total_bytes_sent,omitempty"`
	PacketsReceived    uint64                 `protobuf:"varint,3,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsSent        uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	ErrorsReceived     uint64                 `protobuf:"varint,5,opt,name=errors_received,json=errorsReceived,proto3" json:"errors_received,omitempty"`
	ErrorsSent         uint64                 `protobuf:"varint,6,opt,name=errors_sent,json=errorsSent,proto3" json:"errors_sent,omitempty"`
	DropsReceived      uint64                 `protobuf:"varint,7,opt,name=drops_received,json=dropsReceived,proto3" json:"drops_received,omitempty"`
	DropsSent          uint64                 `protobuf:"varint,8,opt,name=drops_sent,json=dropsSent,proto3" json:"drops_sent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkStats) GetTotalBytesReceived() uint64 {
	if x != nil {
		return x.TotalBytesReceived
	}
	return 0
}

func (x *NetworkStats) GetTotalBytesSent() uint64 {
	if x != nil {
		return x.TotalBytesSent
	}
	return 0
}

func (x *NetworkStats) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *NetworkStats) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetworkStats) GetErrorsReceived() uint64 {
	if x != nil {
		return x.ErrorsReceived
	}
	return 0
}

func (x *NetworkStats) GetErrorsSent() uint64 {
	if x != nil {
		return x.ErrorsSent
	}
	return 0
}

func (x *NetworkStats) GetDropsReceived() uint64 {
	if x != nil {
		return x.DropsReceived
	}
	return 0
}

func (x *NetworkStats) GetDropsSent() uint64 {
	if x != nil {
		return x.DropsSent
	}
	return 0
}

// NetworkTalker represents a top network talker
type NetworkTalker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*NetworkTalker_Protocol
	//	*NetworkTalker_Connection
	Identifier     isNetworkTalker_Identifier `protobuf_oneof:"identifier"`
	BytesPerSecond uint64                     `protobuf:"varint,3,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	Percentage     float64                    `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkTalker) Reset() {
	*x = NetworkTalker{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTalker) ProtoMessage() {}

func (x *NetworkTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTalker.ProtoReflect.Descriptor instead.
func (*NetworkTalker) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkTalker) GetIdentifier() isNetworkTalker_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *NetworkTalker) GetProtocol() *ProtocolTalker {
	if x != nil {
		if x, ok := x.Identifier.(*NetworkTalker_Protocol); ok {
			return x.Protocol
		}
	}
	return nil
}

func (x *NetworkTalker) GetConnection() *ConnectionTalker {
	if x != nil {
		if x, ok := x.Identifier.(*NetworkTalker_Connection); ok {
			return x.Connection
		}
	}
	return nil
}

func (x *NetworkTalker) GetBytesPerSecond() uint64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *NetworkTalker) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type isNetworkTalker_Identifier interface {
	isNetworkTalker_Identifier()
}

type NetworkTalker_Protocol struct {
	Protocol *ProtocolTalker `protobuf:"bytes,1,opt,name=protocol,proto3,oneof"`
}

type NetworkTalker_Connection struct {
	Connection *ConnectionTalker `protobuf:"bytes,2,opt,name=connection,proto3,oneof"`
}

func (*NetworkTalker_Protocol) isNetworkTalker_Identifier() {}

func (*NetworkTalker_Connection) isNetworkTalker_Identifier() {}

// ProtocolTalker identifies traffic by protocol
type ProtocolTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // TCP, UDP, ICMP, etc.
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`        // Optional port for protocol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolTalker) Reset() {
	*x = ProtocolTalker{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolTalker) ProtoMessage() {}

func (x *ProtocolTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolTalker.ProtoReflect.Descriptor instead.
func (*ProtocolTalker) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolTalker) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolTalker) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// ConnectionTalker identifies traffic by connection
type ConnectionTalker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceIp        string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort      uint32                 `protobuf:"varint,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationIp   string                 `protobuf:"bytes,3,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort uint32                 `protobuf:"varint,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectionTalker) Reset() {
	*x = ConnectionTalker{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTalker) ProtoMessage() {}

func (x *ConnectionTalker) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTalker.ProtoReflect.Descriptor instead.
func (*ConnectionTalker) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectionTalker) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ConnectionTalker) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *ConnectionTalker) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *ConnectionTalker) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *ConnectionTalker) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// ListeningSocket represents a listening network socket
type ListeningSocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningSocket) Reset() {
	*x = ListeningSocket{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningSocket) ProtoMessage() {}

func (x *ListeningSocket) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningSocket.ProtoReflect.Descriptor instead.
func (*ListeningSocket) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{9}
}

func (x *ListeningSocket) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ListeningSocket) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListeningSocket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListeningSocket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListeningSocket) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListeningSocket) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// TcpConnectionStates contains counts of TCP connections in various states
type TcpConnectionStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Established   uint32                 `protobuf:"varint,1,opt,name=established,proto3" json:"established,omitempty"`
	SynSent       uint32                 `protobuf:"varint,2,opt,name=syn_sent,json=synSent,proto3" json:"syn_sent,omitempty"`
	SynRecv       uint32                 `protobuf:"varint,3,opt,name=syn_recv,json=synRecv,proto3" json:"syn_recv,omitempty"`
	FinWait1      uint32                 `protobuf:"varint,4,opt,name=fin_wait1,json=finWait1,proto3" json:"fin_wait1,omitempty"`
	FinWait2      uint32                 `protobuf:"varint,5,opt,name=fin_wait2,json=finWait2,proto3" json:"fin_wait2,omitempty"`
	TimeWait      uint32                 `protobuf:"varint,6,opt,name=time_wait,json=timeWait,proto3" json:"time_wait,omitempty"`
	Close         uint32                 `protobuf:"varint,7,opt,name=close,proto3" json:"close,omitempty"`
	CloseWait     uint32                 `protobuf:"varint,8,opt,name=close_wait,json=closeWait,proto3" json:"close_wait,omitempty"`
	LastAck       uint32                 `protobuf:"varint,9,opt,name=last_ack,json=lastAck,proto3" json:"last_ack,omitempty"`
	Listen        uint32                 `protobuf:"varint,10,opt,name=listen,proto3" json:"listen,omitempty"`
	Closing       uint32                 `protobuf:"varint,11,opt,name=closing,proto3" json:"closing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpConnectionStates) Reset() {
	*x = TcpConnectionStates{}
	mi := &file_api_v1_pulsecat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpConnectionStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpConnectionStates) ProtoMessage() {}

func (x *TcpConnectionStates) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pulsecat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpConnectionStates.ProtoReflect.Descriptor instead.
func (*TcpConnectionStates) Descriptor() ([]byte, []int) {
	return file_api_v1_pulsecat_proto_rawDescGZIP(), []int{10}
}

func (x *TcpConnectionStates) GetEstablished() uint32 {
	if x != nil {
		return x.Established
	}
	return 0
}

func (x *TcpConnectionStates) GetSynSent() uint32 {
	if x != nil {
		return x.SynSent
	}
	return 0
}

func (x *TcpConnectionStates) GetSynRecv() uint32 {
	if x != nil {
		return x.SynRecv
	}
	return 0
}

func (x *TcpConnectionStates) GetFinWait1() uint32 {
	if x != nil {
		return x.FinWait1
	}
	return 0
}

func (x *TcpConnectionStates) GetFinWait2() uint32 {
	if x != nil {
		return x.FinWait2
	}
	return 0
}

func (x *TcpConnectionStates) GetTimeWait() uint32 {
	if x != nil {
		return x.TimeWait
	}
	return 0
}

func (x *TcpConnectionStates) GetClose() uint32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *TcpConnectionStates) GetCloseWait() uint32 {
	if x != nil {
		return x.CloseWait
	}
	return 0
}

func (x *TcpConnectionStates) GetLastAck() uint32 {
	if x != nil {
		return x.LastAck
	}
	return 0
}

func (x *TcpConnectionStates) GetListen() uint32 {
	if x != nil {
		return x.Listen
	}
	return 0
}

func (x *TcpConnectionStates) GetClosing() uint32 {
	if x != nil {
		return x.Closing
	}
	return 0
}

var File_api_v1_pulsecat_proto protoreflect.FileDescriptor

const file_api_v1_pulsecat_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/pulsecat.proto\x12\vpulsecat.v1\"\x87\x01\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vstart_delay\x18\x01 \x01(\rR\n" +
	"startDelay\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\rR\tfrequency\x124\n" +
	"\n" +
	"stat_types\x18\x03 \x03(\x0e2\x15.pulsecat.v1.StatTypeR\tstatTypes\"\xf1\x03\n" +
	"\vSystemStats\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12;\n" +
	"\fload_average\x18\x02 \x01(\v2\x18.pulsecat.v1.LoadAverageR\vloadAverage\x122\n" +
	"\tcpu_usage\x18\x03 \x01(\v2\x15.pulsecat.v1.CpuUsageR\bcpuUsage\x125\n" +
	"\n" +
	"disk_usage\x18\x04 \x03(\v2\x16.pulsecat.v1.DiskUsageR\tdiskUsage\x12>\n" +
	"\rnetwork_stats\x18\x05 \x01(\v2\x19.pulsecat.v1.NetworkStatsR\fnetworkStats\x12;\n" +
	"\vtop_talkers\x18\x06 \x03(\v2\x1a.pulsecat.v1.NetworkTalkerR\n" +
	"topTalkers\x12I\n" +
	"\x11listening_sockets\x18\a \x03(\v2\x1c.pulsecat.v1.ListeningSocketR\x10listeningSockets\x12T\n" +
	"\x15tcp_connection_states\x18\b \x01(\v2 .pulsecat.v1.TcpConnectionStatesR\x13tcpConnectionStates\"b\n" +
	"\vLoadAverage\x12\x17\n" +
	"\aone_min\x18\x01 \x01(\x01R\x06oneMin\x12\x19\n" +
	"\bfive_min\x18\x02 \x01(\x01R\afiveMin\x12\x1f\n" +
	"\vfifteen_min\x18\x03 \x01(\x01R\n" +
	"fifteenMin\"\xcf\x01\n" +
	"\bCpuUsage\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x01R\x04user\x12\x16\n" +
	"\x06system\x18\x02 \x01(\x01R\x06system\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x01R\x04idle\x12\x12\n" +
	"\x04nice\x18\x04 \x01(\x01R\x04nice\x12\x16\n" +
	"\x06iowait\x18\x05 \x01(\x01R\x06iowait\x12\x10\n" +
	"\x03irq\x18\x06 \x01(\x01R\x03irq\x12\x19\n" +
	"\bsoft_irq\x18\a \x01(\x01R\asoftIrq\x12\x14\n" +
	"\x05steal\x18\b \x01(\x01R\x05steal\x12\x14\n" +
	"\x05guest\x18\t \x01(\x01R\x05guest\"\xba\x02\n" +
	"\tDiskUsage\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\tR\n" +
	"filesystem\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x04R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x04R\x06usedMb\x12!\n" +
	"\favailable_mb\x18\x04 \x01(\x04R\vavailableMb\x12!\n" +
	"\fused_percent\x18\x05 \x01(\x01R\vusedPercent\x12!\n" +
	"\ftotal_inodes\x18\x06 \x01(\x04R\vtotalInodes\x12\x1f\n" +
	"\vused_inodes\x18\a \x01(\x04R\n" +
	"usedInodes\x12.\n" +
	"\x13used_inodes_percent\x18\b \x01(\x01R\x11usedInodesPercent\x12\x1f\n" +
	"\vmount_point\x18\t \x01(\tR\n" +
	"mountPoint\"\xc8\x02\n" +
	"\fNetworkStats\x120\n" +
	"\x14total_bytes_received\x18\x01 \x01(\x04R\x12totalBytesReceived\x12(\n" +
	"\x10total_bytes_sent\x18\x02 \x01(\x04R\x0etotalBytesSent\x12)\n" +
	"\x10packets_received\x18\x03 \x01(\x04R\x0fpacketsReceived\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12'\n" +
	"\x0ferrors_received\x18\x05 \x01(\x04R\x0eerrorsReceived\x12\x1f\n" +
	"\verrors_sent\x18\x06 \x01(\x04R\n" +
	"errorsSent\x12%\n" +
	"\x0edrops_received\x18\a \x01(\x04R\rdropsReceived\x12\x1d\n" +
	"\n" +
	"drops_sent\x18\b \x01(\x04R\tdropsSent\"\xe3\x01\n" +
	"\rNetworkTalker\x129\n" +
	"\bprotocol\x18\x01 \x01(\v2\x1b.pulsecat.v1.ProtocolTalkerH\x00R\bprotocol\x12?\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1d.pulsecat.v1.ConnectionTalkerH\x00R\n" +
	"connection\x12(\n" +
	"\x10bytes_per_second\x18\x03 \x01(\x04R\x0ebytesPerSecond\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentageB\f\n" +
	"\n" +
	"identifier\"@\n" +
	"\x0eProtocolTalker\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\xbe\x01\n" +
	"\x10ConnectionTalker\x12\x1b\n" +
	"\tsource_ip\x18\x01 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x02 \x01(\rR\n" +
	"sourcePort\x12%\n" +
	"\x0edestination_ip\x18\x03 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x04 \x01(\rR\x0fdestinationPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"\x9b\x01\n" +
	"\x0fListeningSocket\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"\xc6\x02\n" +
	"\x13TcpConnectionStates\x12 \n" +
	"\vestablished\x18\x01 \x01(\rR\vestablished\x12\x19\n" +
	"\bsyn_sent\x18\x02 \x01(\rR\asynSent\x12\x19\n" +
	"\bsyn_recv\x18\x03 \x01(\rR\asynRecv\x12\x1b\n" +
	"\tfin_wait1\x18\x04 \x01(\rR\bfinWait1\x12\x1b\n" +
	"\tfin_wait2\x18\x05 \x01(\rR\bfinWait2\x12\x1b\n" +
	"\ttime_wait\x18\x06 \x01(\rR\btimeWait\x12\x14\n" +
	"\x05close\x18\a \x01(\rR\x05close\x12\x1d\n" +
	"\n" +
	"close_wait\x18\b \x01(\rR\tcloseWait\x12\x19\n" +
	"\blast_ack\x18\t \x01(\rR\alastAck\x12\x16\n" +
	"\x06listen\x18\n" +
	" \x01(\rR\x06listen\x12\x18\n" +
	"\aclosing\x18\v \x01(\rR\aclosing*\xf2\x01\n" +
	"\bStatType\x12\x19\n" +
	"\x15STAT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STAT_TYPE_LOAD_AVERAGE\x10\x01\x12\x17\n" +
	"\x13STAT_TYPE_CPU_USAGE\x10\x02\x12\x18\n" +
	"\x14STAT_TYPE_DISK_USAGE\x10\x03\x12\x1b\n" +
	"\x17STAT_TYPE_NETWORK_STATS\x10\x04\x12\x19\n" +
	"\x15STAT_TYPE_TOP_TALKERS\x10\x05\x12\x1f\n" +
	"\x1bSTAT_TYPE_LISTENING_SOCKETS\x10\x06\x12#\n" +
	"\x1fSTAT_TYPE_TCP_CONNECTION_STATES\x10\a2Y\n" +
	"\rSystemMonitor\x12H\n" +
	"\tSubscribe\x12\x1d.pulsecat.v1.SubscribeRequest\x1a\x18.pulsecat.v1.SystemStats\"\x000\x01B\x11Z\x0fpulsecat/api/v1b\x06proto3"

var (
	file_api_v1_pulsecat_proto_rawDescOnce sync.Once
	file_api_v1_pulsecat_proto_rawDescData []byte
)

func file_api_v1_pulsecat_proto_rawDescGZIP() []byte {
	file_api_v1_pulsecat_proto_rawDescOnce.Do(func() {
		file_api_v1_pulsecat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_pulsecat_proto_rawDesc), len(file_api_v1_pulsecat_proto_rawDesc)))
	})
	return file_api_v1_pulsecat_proto_rawDescData
}

var file_api_v1_pulsecat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_pulsecat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_v1_pulsecat_proto_goTypes = []any{
	(StatType)(0),               // 0: pulsecat.v1.StatType
	(*SubscribeRequest)(nil),    // 1: pulsecat.v1.SubscribeRequest
	(*SystemStats)(nil),         // 2: pulsecat.v1.SystemStats
	(*LoadAverage)(nil),         // 3: pulsecat.v1.LoadAverage
	(*CpuUsage)(nil),            // 4: pulsecat.v1.CpuUsage
	(*DiskUsage)(nil),           // 5: pulsecat.v1.DiskUsage
	(*NetworkStats)(nil),        // 6: pulsecat.v1.NetworkStats
	(*NetworkTalker)(nil),       // 7: pulsecat.v1.NetworkTalker
	(*ProtocolTalker)(nil),      // 8: pulsecat.v1.ProtocolTalker
	(*ConnectionTalker)(nil),    // 9: pulsecat.v1.ConnectionTalker
	(*ListeningSocket)(nil),     // 10: pulsecat.v1.ListeningSocket
	(*TcpConnectionStates)(nil), // 11: pulsecat.v1.TcpConnectionStates
}
var file_api_v1_pulsecat_proto_depIdxs = []int32{
	0,  // 0: pulsecat.v1.SubscribeRequest.stat_types:type_name -> pulsecat.v1.StatType
	3,  // 1: pulsecat.v1.SystemStats.load_average:type_name -> pulsecat.v1.LoadAverage
	4,  // 2: pulsecat.v1.SystemStats.cpu_usage:type_name -> pulsecat.v1.CpuUsage
	5,  // 3: pulsecat.v1.SystemStats.disk_usage:type_name -> pulsecat.v1.DiskUsage
	6,  // 4: pulsecat.v1.SystemStats.network_stats:type_name -> pulsecat.v1.NetworkStats
	7,  // 5: pulsecat.v1.SystemStats.top_talkers:type_name -> pulsecat.v1.NetworkTalker
	10, // 6: pulsecat.v1.SystemStats.listening_sockets:type_name -> pulsecat.v1.ListeningSocket
	11, // 7: pulsecat.v1.SystemStats.tcp_connection_states:type_name -> pulsecat.v1.TcpConnectionStates
	8,  // 8: pulsecat.v1.NetworkTalker.protocol:type_name -> pulsecat.v1.ProtocolTalker
	9,  // 9: pulsecat.v1.NetworkTalker.connection:type_name -> pulsecat.v1.ConnectionTalker
	1,  // 10: pulsecat.v1.SystemMonitor.Subscribe:input_type -> pulsecat.v1.SubscribeRequest
	2,  // 11: pulsecat.v1.SystemMonitor.Subscribe:output_type -> pulsecat.v1.SystemStats
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_v1_pulsecat_proto_init() }
func file_api_v1_pulsecat_proto_init() {
	if File_api_v1_pulsecat_proto != nil {
		return
	}
	file_api_v1_pulsecat_proto_msgTypes[6].OneofWrappers = []any{
		(*NetworkTalker_Protocol)(nil),
		(*NetworkTalker_Connection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_pulsecat_proto_rawDesc), len(file_api_v1_pulsecat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_pulsecat_proto_goTypes,
		DependencyIndexes: file_api_v1_pulsecat_proto_depIdxs,
		EnumInfos:         file_api_v1_pulsecat_proto_enumTypes,
		MessageInfos:      file_api_v1_pulsecat_proto_msgTypes,
	}.Build()
	File_api_v1_pulsecat_proto = out.File
	file_api_v1_pulsecat_proto_goTypes = nil
	file_api_v1_pulsecat_proto_depIdxs = nil
}
