// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/v1/pulsecat.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulseCat_Subscribe_FullMethodName = "/pulsecat.v1.PulseCat/Subscribe"
	PulseCat_Meow_FullMethodName      = "/pulsecat.v1.PulseCat/Meow"
)

// PulseCatClient is the client API for PulseCat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PulseCat service provides real-time system monitoring statistics
type PulseCatClient interface {
	// Subscribe to system statistics stream
	// Client specifies M (start_delay) and N (frequency) parameters
	// Server streams SystemStats messages periodically
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStats], error)
	// Meow is a ping-like endpoint that responds with "Meow!" after a delay
	// If frequency is specified, responses are streamed periodically
	Meow(ctx context.Context, in *MeowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MeowResponse], error)
}

type pulseCatClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseCatClient(cc grpc.ClientConnInterface) PulseCatClient {
	return &pulseCatClient{cc}
}

func (c *pulseCatClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PulseCat_ServiceDesc.Streams[0], PulseCat_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SystemStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseCat_SubscribeClient = grpc.ServerStreamingClient[SystemStats]

func (c *pulseCatClient) Meow(ctx context.Context, in *MeowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MeowResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PulseCat_ServiceDesc.Streams[1], PulseCat_Meow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MeowRequest, MeowResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseCat_MeowClient = grpc.ServerStreamingClient[MeowResponse]

// PulseCatServer is the server API for PulseCat service.
// All implementations must embed UnimplementedPulseCatServer
// for forward compatibility.
//
// PulseCat service provides real-time system monitoring statistics
type PulseCatServer interface {
	// Subscribe to system statistics stream
	// Client specifies M (start_delay) and N (frequency) parameters
	// Server streams SystemStats messages periodically
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SystemStats]) error
	// Meow is a ping-like endpoint that responds with "Meow!" after a delay
	// If frequency is specified, responses are streamed periodically
	Meow(*MeowRequest, grpc.ServerStreamingServer[MeowResponse]) error
	mustEmbedUnimplementedPulseCatServer()
}

// UnimplementedPulseCatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulseCatServer struct{}

func (UnimplementedPulseCatServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SystemStats]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPulseCatServer) Meow(*MeowRequest, grpc.ServerStreamingServer[MeowResponse]) error {
	return status.Error(codes.Unimplemented, "method Meow not implemented")
}
func (UnimplementedPulseCatServer) mustEmbedUnimplementedPulseCatServer() {}
func (UnimplementedPulseCatServer) testEmbeddedByValue()                  {}

// UnsafePulseCatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseCatServer will
// result in compilation errors.
type UnsafePulseCatServer interface {
	mustEmbedUnimplementedPulseCatServer()
}

func RegisterPulseCatServer(s grpc.ServiceRegistrar, srv PulseCatServer) {
	// If the following call panics, it indicates UnimplementedPulseCatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulseCat_ServiceDesc, srv)
}

func _PulseCat_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PulseCatServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SystemStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseCat_SubscribeServer = grpc.ServerStreamingServer[SystemStats]

func _PulseCat_Meow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MeowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PulseCatServer).Meow(m, &grpc.GenericServerStream[MeowRequest, MeowResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulseCat_MeowServer = grpc.ServerStreamingServer[MeowResponse]

// PulseCat_ServiceDesc is the grpc.ServiceDesc for PulseCat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulseCat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulsecat.v1.PulseCat",
	HandlerType: (*PulseCatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PulseCat_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Meow",
			Handler:       _PulseCat_Meow_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/pulsecat.proto",
}
